import { NavItem } from './nav-item/nav-item';
import { TipoEmpresa } from 'src/app/models/empresa/tipo-empresa.enum';

const grafica = [TipoEmpresa.GRAFICA];
const deposito = [TipoEmpresa.DEPOSITO];
const todosSegmentos = [TipoEmpresa.GRAFICA, TipoEmpresa.DEPOSITO];

export const navItems: NavItem[] = [
    {
        navCap: 'Menu'
    },
    {
        displayName: 'Dashboard',
        iconName: 'layout-dashboard',
        bgcolor: 'primary',
        route: '/dashboards/dashboard1',
        allowedEmpresaTipos: grafica,
    },
    {
        displayName: 'Dashboard',
        iconName: 'layout-dashboard',
        bgcolor: 'primary',
        route: '/page/deposito',
        requiredPermission: ['DEPOSITO_DASHBOARD_VER'],
        allowedEmpresaTipos: deposito,
    },
    {
        displayName: 'SmartCalc',
        iconName: 'calculator',
        bgcolor: 'primary',
        route: '/smartcalc',
        allowedEmpresaTipos: grafica,
    },
    {
        navCap: 'Operação',
        allowedEmpresaTipos: todosSegmentos,
    },
    {
        displayName: 'Orçamentos',
        iconName: 'file-text',
        bgcolor: 'primary',
        route: '/page/orcamentos',
        requiredPermission: ['ORCAMENTOS_VER'],
        allowedEmpresaTipos: deposito,
    },
    {
        displayName: 'Pedidos',
        iconName: 'file-text',
        bgcolor: 'primary',
        route: '/page/pedido',
        requiredPermission: ['PEDIDOS_VER', 'PEDIDOS_CADASTRAR'],
        allowedEmpresaTipos: grafica,
    },
    {
        displayName: 'Clientes',
        iconName: 'users',
        bgcolor: 'primary',
        route: '/page/cliente',
        requiredPermission: ['CLIENTE_VER', 'CLIENTE_CADASTRAR', 'CLIENTE_EDITAR', 'CLIENTE_EXCLUIR'],
        allowedEmpresaTipos: todosSegmentos,
    },
    {
        navCap: 'Catálogo',
        allowedEmpresaTipos: todosSegmentos,
    },
    {
        displayName: 'Catálogo',
        iconName: 'package',
        bgcolor: 'primary',
        route: '/page/grafica/produtos',
        requiredPermission: [
            'GRAFICA_PRODUTOS_VER',
            'GRAFICA_PRODUTOS_EDITAR',
            'DEPOSITO_ITENS_VER',
            'DEPOSITO_CATEGORIAS_VER',
            'DEPOSITO_MARCAS_VER',
            'CATALOGO_PRODUTOS_VER',
            'CATALOGO_CATEGORIAS_VER',
            'CATALOGO_MARCAS_VER',
        ],
        allowedEmpresaTipos: todosSegmentos,
        children: [
            { displayName: 'Produtos', iconName: 'point', bgcolor: 'transparent', route: '/page/grafica/produtos', requiredPermission: ['GRAFICA_PRODUTOS_VER'], allowedEmpresaTipos: grafica },
            { displayName: 'Categorias', iconName: 'point', bgcolor: 'transparent', route: '/page/grafica/categorias', requiredPermission: ['GRAFICA_PRODUTOS_VER'], allowedEmpresaTipos: grafica },
            { displayName: 'Materiais', iconName: 'point', bgcolor: 'transparent', route: '/page/grafica/materiais', requiredPermission: ['GRAFICA_PRODUTOS_VER'], allowedEmpresaTipos: grafica },
            { displayName: 'Formatos', iconName: 'point', bgcolor: 'transparent', route: '/page/grafica/formatos', requiredPermission: ['GRAFICA_PRODUTOS_VER'], allowedEmpresaTipos: grafica },
            { displayName: 'Cores', iconName: 'point', bgcolor: 'transparent', route: '/page/grafica/cores', requiredPermission: ['GRAFICA_PRODUTOS_VER'], allowedEmpresaTipos: grafica },
            { displayName: 'Acabamentos', iconName: 'point', bgcolor: 'transparent', route: '/page/grafica/acabamentos', requiredPermission: ['GRAFICA_PRODUTOS_VER'], allowedEmpresaTipos: grafica },
            { displayName: 'Serviços', iconName: 'point', bgcolor: 'transparent', route: '/page/grafica/servicos', requiredPermission: ['GRAFICA_PRODUTOS_VER'], allowedEmpresaTipos: grafica },
            {
                displayName: 'Produtos',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/deposito/itens',
                catalogoModo: 'LEGADO_DEPOSITO',
                requiredPermission: ['DEPOSITO_ITENS_VER'],
                allowedEmpresaTipos: deposito,
            },
            {
                displayName: 'Categorias',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/deposito/categorias',
                catalogoModo: 'LEGADO_DEPOSITO',
                requiredPermission: ['DEPOSITO_CATEGORIAS_VER'],
                allowedEmpresaTipos: deposito,
            },
            {
                displayName: 'Marcas',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/deposito/marcas',
                catalogoModo: 'LEGADO_DEPOSITO',
                requiredPermission: ['DEPOSITO_MARCAS_VER'],
                allowedEmpresaTipos: deposito,
            },
            {
                displayName: 'Produtos',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/catalogo/produtos',
                catalogoModo: 'CATALOGO_NOVO',
                requiredPermission: ['CATALOGO_PRODUTOS_VER'],
                allowedEmpresaTipos: deposito,
            },
            {
                displayName: 'Categorias',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/catalogo/categorias',
                catalogoModo: 'CATALOGO_NOVO',
                requiredPermission: ['CATALOGO_CATEGORIAS_VER'],
                allowedEmpresaTipos: deposito,
            },
            {
                displayName: 'Marcas',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/catalogo/marcas',
                catalogoModo: 'CATALOGO_NOVO',
                requiredPermission: ['CATALOGO_MARCAS_VER'],
                allowedEmpresaTipos: deposito,
            },
        ],
    },
    {
        navCap: 'Gestão',
        allowedEmpresaTipos: todosSegmentos,
    },
    {
        displayName: 'Gestão de Pessoas',
        iconName: 'briefcase',
        bgcolor: 'primary',
        route: '/page/funcionarios',
        requiredPermission: ['FUNCIONARIO_VER', 'FOLHA_VER'],
        allowedEmpresaTipos: grafica,
        children: [
            {
                displayName: 'Funcionários',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/funcionarios',
                requiredPermission: ['FUNCIONARIO_VER'],
                allowedEmpresaTipos: grafica,
            },
            {
                displayName: 'Folha de Pagamento',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/folha-pagamento',
                requiredPermission: ['FOLHA_VER'],
                allowedEmpresaTipos: grafica,
            }
        ]
    },
    {
        displayName: 'Usuários',
        iconName: 'user-circle',
        bgcolor: 'primary',
        route: '/page/usuarios/listar',
        requiredPermission: ['USUARIOS_VER', 'USUARIO_CADASTRAR', 'USUARIO_EDITAR', 'USUARIO_EXCLUIR'],
        allowedEmpresaTipos: todosSegmentos,
    },
    {
        displayName: 'Perfis e Permissões',
        iconName: 'users-group',
        bgcolor: 'primary',
        route: '/page/perfil',
        requiredPermission: ['PERFIS_PERMISSOES_VER', 'PERFIS_PERMISSOES_CADASTRAR', 'PERFIS_PERMISSOES_EDITAR', 'PERFIS_PERMISSOES_EXCLUIR'],
        allowedEmpresaTipos: todosSegmentos,
    },
    {
        navCap: 'Presença Digital',
        allowedEmpresaTipos: todosSegmentos,
    },
    {
        displayName: 'Meu Site',
        iconName: 'world',
        bgcolor: 'primary',
        requiredPermission: ['SITE_BANNERS_VER', 'SITE_PAGINAS_VER', 'SITE_CONFIG_VER'],
        allowedEmpresaTipos: todosSegmentos,
        children: [
            {
                displayName: 'Banners',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/site/banners',
                requiredPermission: ['SITE_BANNERS_VER'],
                allowedEmpresaTipos: todosSegmentos,
            },
            {
                displayName: 'Páginas',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/site/paginas',
                requiredPermission: ['SITE_PAGINAS_VER'],
                allowedEmpresaTipos: todosSegmentos,
            },
            {
                displayName: 'Configurações',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/site/configuracoes',
                requiredPermission: ['SITE_CONFIG_VER'],
                allowedEmpresaTipos: todosSegmentos,
            }
        ]
    },
    {
        displayName: 'ClickLink',
        iconName: 'link',
        bgcolor: 'primary',
        featureKey: 'LINKS',
        requiredPermission: ['LINKS_VER'],
        allowedEmpresaTipos: todosSegmentos,
        children: [
            {
                displayName: 'Páginas',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/links/paginas',
                featureKey: 'LINKS',
                requiredPermission: ['LINKS_VER'],
                allowedEmpresaTipos: todosSegmentos,
            },
            {
                displayName: 'Analytics',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/links/analytics',
                featureKey: 'LINKS',
                requiredPermission: ['LINKS_VER'],
                allowedEmpresaTipos: todosSegmentos,
            },
        ],
    },
    {
        displayName: 'ClickTV',
        iconName: 'device-tv',
        bgcolor: 'primary',
        route: '/page/clicktv/midias',
        requiredPermission: ['CLICKTV_VER', 'CLICKTV_MIDIAS_GERENCIAR', 'CLICKTV_PLAYLISTS_GERENCIAR', 'CLICKTV_TELAS_GERENCIAR'],
        allowedEmpresaTipos: todosSegmentos,
        children: [
            {
                displayName: 'Mídias',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/clicktv/midias',
                requiredPermission: ['CLICKTV_VER', 'CLICKTV_MIDIAS_GERENCIAR'],
                allowedEmpresaTipos: todosSegmentos,
            },
            {
                displayName: 'Playlists',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/clicktv/playlists',
                requiredPermission: ['CLICKTV_VER', 'CLICKTV_PLAYLISTS_GERENCIAR'],
                allowedEmpresaTipos: todosSegmentos,
            },
            {
                displayName: 'Telas',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/clicktv/telas',
                requiredPermission: ['CLICKTV_VER', 'CLICKTV_TELAS_GERENCIAR'],
                allowedEmpresaTipos: todosSegmentos,
            },
        ]
    },
    {
        navCap: 'Configurações',
        allowedEmpresaTipos: todosSegmentos,
    },
    {
        displayName: 'Dados da empresa',
        iconName: 'building',
        bgcolor: 'primary',
        route: '/page/empresa',
        requiredPermission: ['DADOS_EMPRESA'],
        allowedEmpresaTipos: todosSegmentos,
    },
    {
        displayName: 'Minha assinatura',
        iconName: 'credit-card',
        bgcolor: 'primary',
        route: '/billing/minha-assinatura',
        allowedEmpresaTipos: todosSegmentos,
        proprietarioOnly: true,
    },
    {
        displayName: 'Configurações',
        iconName: 'settings-automation',
        bgcolor: 'primary',
        route: '/config',
        allowedEmpresaTipos: todosSegmentos,
        children: [
            {
                displayName: 'SmartCalc',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/calculadora/config/criar',
                requiredPermission: ['CONFIG_CALCULADORAS'],
                allowedEmpresaTipos: grafica,
            },
            {
                displayName: 'Presença Pública',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/config/presenca-publica',
                requiredPermission: ['DADOS_EMPRESA'],
                allowedEmpresaTipos: todosSegmentos,
            },
            {
                displayName: 'Aplicativos e atalhos',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/config/aplicativos-atalhos',
                requiredPermission: ['CONFIGURACOES_APLICATIVOS_ATALHOS_VER', 'CONFIGURACOES_APLICATIVOS_ATALHOS_EDITAR'],
                allowedEmpresaTipos: todosSegmentos,
            },
            {
                displayName: 'Calculadora de Materiais',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/calculadora-materiais',
                featureKey: 'CALCULADORA_MATERIAIS',
                requiredPermission: ['CALCULADORA_MATERIAIS_CONFIGURAR'],
                allowedEmpresaTipos: todosSegmentos,
            },
            {
                displayName: 'Servidor de E-mail',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/config/email-servidor',
                requiredPermission: ['CONFIG_EMAIL'],
                allowedEmpresaTipos: grafica,
            },
            {
                displayName: 'Folha (Gestão de Pessoas)',
                iconName: 'point',
                bgcolor: 'transparent',
                route: '/page/config/folha-pagamento',
                requiredPermission: ['FOLHA_CONFIGURAR'],
                allowedEmpresaTipos: grafica,
            }
        ]
    },
    {
        navCap: 'Ajuda',
        allowedEmpresaTipos: todosSegmentos,
    },
    {
        displayName: 'Suporte',
        iconName: 'lifebuoy',
        bgcolor: 'primary',
        route: '/page/suporte',
        allowedEmpresaTipos: todosSegmentos,
    },
    {
        displayName: 'Central de ajuda',
        iconName: 'help',
        bgcolor: 'primary',
        route: '/page/ajuda',
        allowedEmpresaTipos: todosSegmentos,
    },
];
